Re-enable FIWARE support
CESARBR/knot-fog-connector pull request #46
Opened 2019-12-23 21:49 UTC by lcbm

(Thanks for sending a pull request! Please fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------

This pull request re-enables FIWARE cloud support. 

Does this close any currently open issues?
------------------------------------------
(Use the special github keywords to reference issues: https://help.github.com/en/articles/closing-issues-using-keywords)

N/A :smiley: 

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://pastebin.com/ and insert the link here.)

N/A :smiley: 

Any other comments?
-------------------

Nope :smiley: 

Where has this been tested?
---------------------------
(Describe your environment setup here.)

**Operating System/Platform:** Linux 5.4.6-arch1-1 x86_64 GNU/Linux
**NPM Version:** v13.5.0 (via [nvm](https://github.com/nvm-sh/nvm) v0.35.2)
**NodeJS Version:** 6.13.4  (via [nvm](https://github.com/nvm-sh/nvm)  v0.35.2)

(Add more information here if needed.)

This commit reverts 757e9cf79cb90d088fc1507ebb2d1286a73afa29.

2019-12-23 21:56 UTC, lcbm commented
This **draft PR** will be **ready for review** when [knot-fog-connector-fiware's v3.0.0 bump PR](https://github.com/CESARBR/knot-fog-connector-fiware/pull/18) is approved, so that `package-lock.json` can be updated with the published npm package info.

2019-12-24 12:54 UTC, ramonhpr commented
Since the PR https://github.com/CESARBR/knot-fog-connector-fiware/pull/18 is approved I'm removing this from draft.

2019-12-24 12:58 UTC, ramonhpr requested changes
About commit description: This commit/patch reverts <hash>

2019-12-24 14:12 UTC, lcbm commented
> About commit description: This commit/patch reverts

Before committing, I was actually in between what you suggested and as is :stuck_out_tongue: 

I opted to leave it as is because it seems that it's a pretty standard convention across repositories (e.g.: [angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#revert) and [electron](https://github.com/electron/electron/blob/eb2d2264d02abd7f34df36809d44752aaf93da93/patches/v8/revert_cleanup_switch_offset_of_to_offsetof_where_possible.patch)).

I can change it, though. Just let me know what you think! :smiley:

2019-12-26 12:35 UTC, netoax requested changes

2019-12-26 12:35 UTC, joaoaneto commented on package.json
> +    "@cesarbr/knot-fog-connector-fiware": "2.0.0",
3.0.0

2019-12-26 17:36 UTC, lcbm commented on package.json
> +    "@cesarbr/knot-fog-connector-fiware": "2.0.0",
Updated! :smile:

2019-12-26 18:20 UTC, ramonhpr approved these changes

2019-12-26 18:37 UTC, netoax approved these changes

2019-12-26 18:37 UTC, merged