Add change log
CESARBR/knot-fog-connector pull request #5
Opened 2019-06-18 23:20 UTC by figueredo

2019-06-24 23:21 UTC, netoax approved these changes

2019-06-25 14:14 UTC, netoax requested changes

2019-06-25 14:14 UTC, joaoaneto commented on CHANGELOG.md
> +### Bug Fixes
Is this a copy/paste mistake?

2019-06-25 17:26 UTC, figueredo commented on CHANGELOG.md
> +### Bug Fixes
Yeap

2019-06-25 17:33 UTC, figueredo commented on CHANGELOG.md
> +### Bug Fixes
Fixed

2019-06-26 11:03 UTC, netoax approved these changes

2019-06-26 11:03 UTC, merged