Update connector with the new update config event
CESARBR/knot-fog-connector pull request #64
Opened 2020-09-22 14:29 UTC by Igoraamc

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
         Update config event.

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

**Testing environment:**

- Operating System/Platform: macOS Catalina
- Node version: v12.16.0
- NPM version: 6.13.4

2020-09-22 18:33 UTC, asf89 approved these changes
Great patch! 😃

2020-09-22 18:36 UTC, esdrasjnr requested changes
Great, just left one comment I think that should be fixed 👍🏻 Let me know if you have any questions about it 😃

2020-09-22 18:36 UTC, esdrasjnr commented on src/interactors/interactors.test.js
>    ],
`sensorId` should be inside the `config` list. Note that the config field hold the list of thing's sensors (and actuators) and its configurations, including the ID (denoted as `sensorId`).

2020-09-22 18:56 UTC, Igoraamc commented on src/interactors/interactors.test.js
>    ],
Yeah, that was my bad!

Done!

2020-09-22 18:58 UTC, esdrasjnr approved these changes
Excellent! 💯

2020-10-22 12:35 UTC, CaioCordeiro approved these changes
LGTM! Great Patch! 😄

2020-11-19 12:27 UTC, netoax approved these changes
LGTM!

2020-11-19 12:27 UTC, merged